cabal-version: 3.0
name:           program
version:        0.1.0.0
build-type:     Simple

executable program
  main-is:          Main.hs
  build-depends:    base ^>= 4.20
  default-language: Haskell2010

executable types
  main-is:          excercises/Types.hs
  build-depends:    base ^>= 4.20
  default-language: Haskell2010